/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness probe — used by the Docker healthcheck.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/create_corpus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Index ``sources`` into a new corpus, register it, return its :class:`CorpusInfo`.
         * @description Index ``sources`` into a new corpus, register it, return its :class:`CorpusInfo`.
         *
         *             Args:
         *                 sources: the corpus — a list of text documents.
         *                 embedder: the embedder, as a string the DI seam resolves
         *                     (:func:`~ef.embedder_adapters.as_embedder`) — ``"hashing"``,
         *                     ``"openai:text-embedding-3-small"``, ``"cohere:..."``, an
         *                     ``http(s)://`` URL, …. ``None`` →
         *                     :data:`~ef.source_manager.DEFAULT_EMBEDDER`, the dependency-free
         *                     :class:`~ef.embedders.HashingEmbedder`.
         *                 segmenter: the segmenter, as a string
         *                     (:func:`~ef.segmenter_adapters.as_segmenter`) — ``None`` → the
         *                     recursive-character default.
         *                 corpus_id: the handle to register the corpus under; ``None`` → a
         *                     fresh random id. Reusing a live id is an error.
         *
         *             Returns:
         *                 the :class:`CorpusInfo` of the freshly indexed corpus.
         *
         *             Raises:
         *                 ValueError: if ``corpus_id`` is already registered.
         */
        post: operations["create_corpus_create_corpus_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search a registered corpus — up to ``limit`` ranked :class:`~ef.source_manager.SearchHit`\ s.
         * @description Search a registered corpus — up to ``limit`` ranked :class:`~ef.source_manager.SearchHit`\ s.
         *
         *             Each hit carries the matched :class:`~ef.segments.Segment`, its
         *             similarity ``score`` (higher = closer) and the ``source_id`` it was cut
         *             from.
         *
         *             Raises:
         *                 KeyError: if ``corpus_id`` is not registered.
         */
        post: operations["search_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/retrieve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Retrieve ranked :class:`~ef.segments.Segment`\ s — the RAG-plug-in shape.
         * @description Retrieve ranked :class:`~ef.segments.Segment`\ s — the RAG-plug-in shape.
         *
         *             Like :meth:`search`, but returns plain segments in rank order (the
         *             ``score`` dropped, the ``source_id`` folded into ``metadata["source"]``)
         *             — clean context to hand to an external RAG/agent framework. ``ef``
         *             returns context; it does not synthesize answers.
         *
         *             Raises:
         *                 KeyError: if ``corpus_id`` is not registered.
         */
        post: operations["retrieve_retrieve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/explore_corpus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Project & cluster a registered corpus — the corpus-map surface.
         * @description Project & cluster a registered corpus — the corpus-map surface.
         *
         *             Runs :func:`ef.exploration.explore` over the corpus: every indexed
         *             segment is projected to ``dims`` coordinates and assigned a cluster,
         *             returned as a row-aligned :class:`~ef.exploration.ExploreResult` (``ids`` /
         *             ``coords`` / ``labels`` / ``cluster_titles``) — the JSON-friendly shape
         *             an ``app_ef`` corpus map consumes.
         *
         *             Args:
         *                 corpus_id: the corpus to explore.
         *                 dims: projection target dimensionality — ``2`` or ``3``.
         *                 projection_method: ``"auto"`` / ``"umap"`` / ``"pca"``.
         *                 cluster_method: ``"kmeans"`` / ``"hdbscan"``.
         *                 n_clusters: number of k-means clusters.
         *                 label: when ``True``, also name each cluster with an LLM (needs the
         *                     ``ef[imbed]`` extra and a key); default ``False``.
         *
         *             Raises:
         *                 KeyError: if ``corpus_id`` is not registered.
         *                 ValueError: if the corpus has fewer than 2 indexed segments.
         */
        post: operations["explore_corpus_explore_corpus_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/corpus_info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Return the :class:`CorpusInfo` of a registered corpus.
         * @description Return the :class:`CorpusInfo` of a registered corpus.
         *
         *             Raises:
         *                 KeyError: if ``corpus_id`` is not registered.
         */
        post: operations["corpus_info_corpus_info_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/list_corpora": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Return the :class:`CorpusInfo` of every registered corpus.
         * @description Return the :class:`CorpusInfo` of every registered corpus.
         */
        post: operations["list_corpora_list_corpora_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/delete_corpus": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Drop a corpus from the registry, releasing its index.
         * @description Drop a corpus from the registry, releasing its index.
         *
         *             Raises:
         *                 KeyError: if ``corpus_id`` is not registered.
         */
        post: operations["delete_corpus_delete_corpus_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description A JSON-friendly summary of one registered corpus.
         *
         *     The return shape shared by :meth:`EfService.create_corpus`,
         *     :meth:`EfService.corpus_info` and (as a list) :meth:`EfService.list_corpora`
         *     — a plain ``dict`` an HTTP client and ``qh``'s schema both understand.
         *
         *     Keys:
         *         corpus_id: the registry handle — how every other method addresses it.
         *         n_sources: the number of source documents in the corpus.
         *         n_segments: the number of indexed segments (sources cut by the segmenter).
         *         embedder: the embedder's ``model_id`` (e.g. ``"hashing:v1@512"``).
         *         dim: the embedding dimensionality.
         *         config_id: the content hash of the segmenter+embedder pipeline.
         */
        CorpusInfo: {
            corpus_id: string;
            n_sources: number;
            n_segments: number;
            embedder: string;
            dim: number;
            config_id: string;
        };
        /**
         * @description A piece of text carved from a source document — the interchange type.
         *
         *     A ``TypedDict``: a :class:`Segment` *is* a plain ``dict``, which keeps it
         *     cheap to create and stream. ``total=False`` because most keys are optional;
         *     by convention ``text`` is always present and ``id`` is always set (derived
         *     from ``text`` if not supplied).
         *
         *     Keys:
         *         text: The segment's text. **Required.**
         *         id: Stable identifier — content-derived by default (:func:`segment_id`).
         *         parent_id: Id of the source document or parent segment this came from.
         *         start: Character offset of the segment's start in the source text.
         *         end: Character offset of the segment's end (exclusive) in the source.
         *         index: Ordinal position of the segment in its segmenter's output.
         *         tokens: Token count of ``text`` (meaningful only with ``metadata`` key
         *             ``tokenizer`` recording which tokenizer counted it).
         *         metadata: Free-form mapping; framework-specific keys live here. See
         *             :data:`PROMOTED_METADATA_KEYS` for the conventional keys.
         */
        Segment: {
            text?: string;
            id?: string;
            parent_id?: string;
            start?: number;
            end?: number;
            index?: number;
            tokens?: number;
            metadata?: {
                [key: string]: unknown;
            };
        };
        /**
         * @description One ranked search result — a :class:`~ef.segments.Segment` and its score.
         *
         *     :meth:`SearchableCorpus.search` / :meth:`SourceManager.search` return a
         *     ranked ``list`` of these. Keeping :class:`~ef.segments.Segment` (the
         *     interchange ``TypedDict``) pure of a result-only ``score`` key, a
         *     :class:`SearchHit` *wraps* it alongside the similarity ``score`` and the
         *     ``source_id`` of the document the segment was cut from.
         *
         *     Attributes:
         *         segment: the matched segment — the canonical :class:`~ef.segments.Segment`.
         *         score: the similarity score from the vector store (higher = closer).
         *         source_id: the corpus key of the source document, if recorded.
         *
         *     >>> hit = SearchHit(segment={'text': 'hi', 'id': 'x'}, score=0.9, source_id='doc-1')
         *     >>> hit.segment['text'], hit.score, hit.source_id
         *     ('hi', 0.9, 'doc-1')
         */
        SearchHit: {
            segment: components["schemas"]["Segment"];
            score: number;
            source_id?: string | null;
        };
        /**
         * @description A structured, JSON-friendly corpus-exploration result.
         *
         *     What :func:`explore` returns and :meth:`ef.service.EfService.explore_corpus`
         *     serves. Every list is **row-aligned**: ``ids[i]``, ``coords[i]`` and
         *     ``labels[i]`` all describe the same item.
         *
         *     Keys:
         *         ids: the per-item identifiers — a corpus's keys, or positional ``"0"``,
         *             ``"1"``, … for an id-less vector matrix.
         *         coords: the projected coordinates — one ``[x, y]`` (or ``[x, y, z]``)
         *             row per item.
         *         labels: the cluster id of each item (HDBSCAN marks noise ``-1``).
         *         cluster_titles: ``{cluster_id: title}`` — empty unless :func:`explore`
         *             was called with ``label=True``.
         */
        ExploreResult: {
            ids: string[];
            coords: number[][];
            labels: number[];
            cluster_titles: {
                [key: string]: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    create_corpus_create_corpus_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    sources: string[];
                    embedder?: string | null;
                    segmenter?: string | null;
                    corpus_id?: string | null;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorpusInfo"];
                };
            };
        };
    };
    search_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    corpus_id: string;
                    query: string;
                    limit?: number;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchHit"][];
                };
            };
        };
    };
    retrieve_retrieve_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    corpus_id: string;
                    query: string;
                    limit?: number;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Segment"][];
                };
            };
        };
    };
    explore_corpus_explore_corpus_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    corpus_id: string;
                    dims?: number;
                    projection_method?: string;
                    cluster_method?: string;
                    n_clusters?: number;
                    label?: boolean;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExploreResult"];
                };
            };
        };
    };
    corpus_info_corpus_info_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    corpus_id: string;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorpusInfo"];
                };
            };
        };
    };
    list_corpora_list_corpora_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CorpusInfo"][];
                };
            };
        };
    };
    delete_corpus_delete_corpus_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    corpus_id: string;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": null;
                };
            };
        };
    };
}
